include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: true
    prefer_const_constructors: false
    prefer_single_quotes: false
    #true: 不能使用 forEach, false: 可以使用 forEach
    avoid_function_literals_in_foreach_calls: false
    lines_longer_than_80_chars: true
