// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSI2u293YCXkx_0Hs0Wq10LAq-D9DvujQ',
    appId: '1:1031695953581:web:52107e7c43b38dee856024',
    messagingSenderId: '1031695953581',
    projectId: 'musiclight-3be05',
    authDomain: 'musiclight-3be05.firebaseapp.com',
    storageBucket: 'musiclight-3be05.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJISzSBe63BCNDQFggt2kksIK56N20PwY',
    appId: '1:1031695953581:android:8bc75006647c4904856024',
    messagingSenderId: '1031695953581',
    projectId: 'musiclight-3be05',
    storageBucket: 'musiclight-3be05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzh0QRfySx-1R14nZrt8MSZigDMB--VE8',
    appId: '1:1031695953581:ios:9d816906357c1f4a856024',
    messagingSenderId: '1031695953581',
    projectId: 'musiclight-3be05',
    storageBucket: 'musiclight-3be05.appspot.com',
    iosBundleId: 'com.example.letApiFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzh0QRfySx-1R14nZrt8MSZigDMB--VE8',
    appId: '1:1031695953581:ios:84840c6c3a28e403856024',
    messagingSenderId: '1031695953581',
    projectId: 'musiclight-3be05',
    storageBucket: 'musiclight-3be05.appspot.com',
    iosBundleId: 'com.example.letApiFlutter.RunnerTests',
  );
}
