// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4AxLyHQHM5qSuMaIX_F8ATMX4rnoFAYU',
    appId: '1:1025745275939:web:24465d098734de6751b596',
    messagingSenderId: '1025745275939',
    projectId: 'let-api-flutter',
    authDomain: 'let-api-flutter.firebaseapp.com',
    storageBucket: 'let-api-flutter.appspot.com',
    measurementId: 'G-FDPZL8D0Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg6-0UReB9E-C5bnLGAwDE7Ks75v--KbU',
    appId: '1:1025745275939:android:5f961f825f907ace51b596',
    messagingSenderId: '1025745275939',
    projectId: 'let-api-flutter',
    storageBucket: 'let-api-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrrzipodY7G9vw0Je6gsAFoHVsE1NtjFc',
    appId: '1:1025745275939:ios:af5d16dd01bfb31f51b596',
    messagingSenderId: '1025745275939',
    projectId: 'let-api-flutter',
    storageBucket: 'let-api-flutter.appspot.com',
    iosClientId:
        '1025745275939-6pf1of6itrk0k69s0pneu2a9jovral21.apps.googleusercontent.com',
    iosBundleId: 'com.example.letApiFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrrzipodY7G9vw0Je6gsAFoHVsE1NtjFc',
    appId: '1:1025745275939:ios:9737106ac85f7fce51b596',
    messagingSenderId: '1025745275939',
    projectId: 'let-api-flutter',
    storageBucket: 'let-api-flutter.appspot.com',
    iosClientId:
        '1025745275939-aaulat3e2av7qmhaepe3ehc3mvgp086s.apps.googleusercontent.com',
    iosBundleId: 'com.example.letApiFlutter.RunnerTests',
  );
}
